# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Site settings
title: "James Vashiri"
email: "james.vashiri@marquette.edu"
description: "Software Engineer & AI Enthusiast | MS in Computer & Information Science | Milwaukee, WI"
baseurl: "" # 
url: "https://vashirij.github.io"
logo: "/assets/images/profile-pic.jpg"
# Site settings
...
sass:
  style: compressed
# Include custom CSS
include:
  - _assets/css/custom.css

# Author
author:
  name: "James Vashiri"
  bio: "Software Engineer & AI Enthusiast | MS Student at Marquette University"
  location: "Milwaukee, WI"
  github: "vashirij"
  linkedin: "https://linkedin.com/in/jvashiri"

# Navigation
header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md

# Build settings
markdown: kramdown
