# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Site settings
title: "James Vashiri"
email: "grinefalcon2@gmail.com"
description: "MS in Computer & Information Science | AI, Cybersecurity, IoT | Research & Project Portfolio"
baseurl: "" # 
url: "https://vashirij.github.io"
logo: "/assets/images/profile-pic.jpg"
# Site settings
...
sass:
  style: compressed
# Include custom CSS
include:
  - _assets/css/custom.css

# Author
author:
  name: "James Vashiri"
  bio: "MS in Computer & Information Science | AI in Agriculture, Cybersecurity, IoT"
  location: "Zimbabwe / United States"
  github: "jvashiri"
  linkedin: "https://linkedin.com/in/jvashiri"

# Navigation
header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md

# Build settings
markdown: kramdown
