remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
# Site settings
title: "James Vashiri"
email: "grinefalcon2@gmail.com"
description: "MS in Computer & Information Science | AI, Cybersecurity, IoT | Research & Project Portfolio"
baseurl: "" # Leave empty for username.github.io
url: "https://vashirij.github.io"
theme: minimal-mistakes-jekyll
logo: "/assets/images/profile-pic.png"

# Author
author:
  name: "James Vashiri"
  bio: "MS Computer & Information Science | AI in Agriculture, Cybersecurity, IoT"
  location: "Zimbabwe / United States"
  github: "jvashiri"
  linkedin: "https://linkedin.com/in/jvashiri"

# Navigation
header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
